"""initial migration

Revision ID: d5acee8ac882
Revises: 
Create Date: 2025-07-17 20:37:11.071417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5acee8ac882'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.add_column('recipes', sa.Column('ingredients', sa.Text(), nullable=False))
    op.drop_column('recipes', 'ingridients')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.add_column('recipes', sa.Column('ingridients', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('recipes', 'ingredients')
    op.create_table('rating',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='rating_recipe_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='rating_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rating_pkey')
    )
    # ### end Alembic commands ###
